### ISSUE TITLE
Command Sqlmc not found

### ISSUE THREAD

**Issue by kinan-Q** [malvads/sqlmc#1]
After successfully running `pip3 install sqlmc` and installing the required dependencies, I encounter an issue when attempting to execute the command `sqlmc -u http:// ...`. it says sqlmc is not found. Am I missing something or doing something wrong? 

thanks .

**Comment by malvads** [comment]
I need more info, can you please reinstall and provide me the logs? thx :)

**Comment by kinan-Q** [comment]
Thanks for your quick reply! I must apologize for my oversight in not double-checking the installation directory for the packages. It's all sorted now, and everything's working fine and tested few websites now. thank you
